{% set name = "pymatgen-analysis-diffusion" %}
{% set version = "2024.7.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 66e628f44127b34d3d652c90aa6b447b282e27daca92c642fda193b38af2288a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.25.0,<2.0
    - joblib
    - pymatgen >=2024.6.10
    - python >=3.6
    - ase
    - seaborn

test:
  imports:
    - pymatgen.analysis.diffusion
    - pymatgen.analysis.diffusion.aimd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsvirtuallab/pymatgen-diffusion/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: This add-on to pymatgen provides tools for analyzing diffusion in materials.
  description: |
    Formerly pymatgen-diffusion, this is an add-on to pymatgen for
    diffusion analysis that is developed by the Materials Virtual Lab.
    Note that it relies on pymatgen for structural manipulations, file
    io, and preliminary analyses. This is and will always be, a scientific
    work in progress. Pls check back regularly for more details.
  doc_url: https://guide.materialsvirtuallab.org/pymatgen-diffusion/
  dev_url: https://github.com/materialsvirtuallab/pymatgen-diffusion/

extra:
  recipe-maintainers:
    - jan-janssen
