schema_version: 1

context:
  name: pymatgen-analysis-diffusion
  version: "2025.11.15"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 3bfaf42ddedf8af23277d1b09bbb916bf71d5f8631c49878e2a9ff3124300a09

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - numpy >=1.25.0,<3.0
    - joblib
    - pymatgen >=2024.6.10
    - python >=${{ python_min }}
    - ase
    - seaborn

tests:
  - python:
      imports:
        - pymatgen.analysis.diffusion
        - pymatgen.analysis.diffusion.aimd
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: This add-on to pymatgen provides tools for analyzing diffusion in materials.
  description: |
    Formerly pymatgen-diffusion, this is an add-on to pymatgen for
    diffusion analysis that is developed by the Materials Virtual Lab.
    Note that it relies on pymatgen for structural manipulations, file
    io, and preliminary analyses. This is and will always be, a scientific
    work in progress. Pls check back regularly for more details.
  homepage: https://github.com/materialsvirtuallab/pymatgen-diffusion/
  repository: https://github.com/materialsvirtuallab/pymatgen-diffusion/
  documentation: https://guide.materialsvirtuallab.org/pymatgen-diffusion/

extra:
  recipe-maintainers:
    - jan-janssen
